/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/caja.glb --name model
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/caja.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0, -0.125]} scale={0.008}>
        <mesh geometry={nodes['14040_Cardboard_Box_On_Palette_v1_L1'].geometry} material={materials.CustomTwo} />
        <mesh geometry={nodes['14040_Cardboard_Box_On_Palette_v1_L1_1'].geometry} material={materials.CustomTrhe} />
      </group>
    </group>
  )
}

useGLTF.preload('/caja.glb')
